# noinspection PyUnresolvedReferences
from mjregrasping.cfg import ParamsConfig

# These values are considered const by convention
hp = {
    "n_grasp_samples":                 20,
    "horizon":                         15,
    "n_samples":                       50,
    "threading_n_samples":             10,
    "temp":                            0.15,
    "keypoint_weight":                 1.0,
    "next_xpos_sdf_weight":            0.1,
    "torso_weight":                    0.5,
    "reachability_weight":             0.0001,
    "grasp_pos_weight":                1.0,
    "trap_weight":                     50.0,
    "grasp_finger_weight":             0.5,
    "grasp_loc_diff_thresh":           0.025,  # A percentage of rope length
    "smoothness_weight":               0.05,
    "angle_cost_weight":               0.25,  # for ThreadingGoal
    "thread_geodesic_w":               20.0,
    "final_keypoint_dist_weight":      20.0,
    "unstable_weight":                 100,
    "reachablility_weight":            1.1,
    "ever_not_grasping_weight":        5.0,
    "finger_q_open":                   0.3,
    "finger_q_closed":                 0.06,
    "finger_q_pregrasp":               0.12,
    "state_history_size":              8,
    "warmstart":                       8,
    "settle_steps":                    10,
    "contact_exponent":                0.5,
    "nongrasping_rope_contact_weight": 0.5,
    "nongrasping_rope_dist_weight":    0.15,
    "gripper_to_goal_weight":          1.0,
    "robot_dq_weight1":                0.01,
    "robot_dq_weight2":                0.5,
    "rope_dq_weight":                  6.0,
    "max_contact_cost":                1,
    "max_expected_contacts":           6,
    "contact_cost":                    3.0,
    "rope_disp_weight":                25.0,
    "eq_err_weight":                   400.0,
    "trap_q_rope_weight":              0.5,
    "frac_dq_threshold":               0.20,
    "max_max_dq":                      0.0075,
    "grasp_goal_radius":               0.045,
    "sub_time_s":                      0.20,
    "min_sub_time_s":                  0.10,
    "max_sub_time_s":                  0.30,
    "geodesic_weight":                 30.0,
    "joint_kp":                        6.0,
    "act_windup_limit":                0.02,
    "start_state_jiggle_deg":          2,
    "wang_scootch_fraction":           0.03,
    "ours_scootch_fraction":           0.005,
    # Use 5 for a 'fast' baseline (still slower than our method), and 50 for strong baseline
    "tamp_horizon":                    5,  # 50,
    "untangle_max_iters":              300,
    "use_signature_cost":              True,
}
